### ISSUE TITLE
[RESEARCH] Limits

### ISSUE THREAD

**Issue by sergeevabc** [Frederikam/fred.moe#3]
Dear Frederik,
Could you be so kind to tell what limits are imposed on fred.moe uploads in terms of size and expiration?

**Comment by freyacodes** [comment]
There's no expiration.

Upload size limit depends on the config
https://github.com/Frederikam/fred.moe/blob/master/application.properties

**Comment by sergeevabc** [comment]
And it seems there is no way to delete the previously uploaded file. What do you think is the primary scenario for using fred.moe then? Uploading non-sensitive screenshots to publish on issue trackers?

**Comment by freyacodes** [comment]
fred.moe is not about storing sensitive information. At first you will get a combination of 3 characters eg like `X-Z.filetype`, making it easy to guess URLs. fred.moe is developed with two use cases in mind:

1. Using a personal domain (eg fred.moe) for file sharing with relative ease.
2. Using very short URLs eg like `https://fred.moe/po9.png` which you could spell out for someone.

**Comment by sergeevabc** [comment]
Thank you, Frederik. These details could be helpful for others.

**Comment by sergeevabc** [comment]
Err… Frederick, ```application.properties``` mentions file size limit, but says nothing about expiration.

**Comment by freyacodes** [comment]
Files do not expire, however that could be accomplished with a cronjob.

**Comment by sergeevabc** [comment]
@Frederikam, fred.moe is no longer accessible, what’s happened?

**Comment by freyacodes** [comment]
@sergeevabc sorry about that. I think the reverse proxy went down because it couldn't renew its Let's Encrypt certificate due to API changes.

**Comment by sergeevabc** [comment]
> Uploads are temporarily disabled!
> I have moved things to a CDN. Uploads will be enabled again when I get around to implementing the new CDN. Your files are still safe, and are now served much faster than before.

@Frederikam, could you be so kind to update about it? Year is 2021.

**Comment by freyacodes** [comment]
I don't have any intention of fixing this. And if I were to, I would probably not allow public uploads.
